### ISSUE TITLE
JUTE + Selenium Grid fails, causes JUTE server to stop

### ISSUE THREAD

**Issue by eculver** [zzo/JUTE#2]
Not sure if this is just a lack fo know-how on my part, but when I try to send tests to Selenium Grid, I'm seeing this error:

jute_submit_test --sh 192.168.0.87 --send_output -t path/to/my/test/test.html  
Submitting { tests: 'path/to/my/test/test.html',
  retry: 0,
  sel_host: '192.168.0.87',
  sel_browser: '*firefox',
  send_output: 1 } to my.hostname.com
Problem contacting JUTE server at: my.hostname.com:8080
Is JUTE running there?  Did you specify '--host' and '--port' correctly?

JUTE server is running, I can connect and run test via web UI, but when I run this command, the server dies. In the log:

[Mon, 12 Sep 2011 22:57:41 GMT] "GET /jute/_get_test?d=1315868261208 HTTP/1.1" 200 - "http://my.hostname.com:8080/jute_docs/run_tests.html?" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.220 Safari/535.1"
{ tests: 'path/to/my/test/test.html',
  retry: 0,
  sel_host: '192.168.0.87',
  sel_browser: '*firefox',
  send_output: 1 }

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ECONNREFUSED, Connection refused
    at Client._onConnect (net.js:601:18)
    at IOWatcher.onWritable [as callback](net.js:186:12)

**Comment by zzo** [comment]
First - is there a Selenium grid running on 192.168.0.87 port 4444?
Seems like JUTE is barfing because it cannot connect to your grid?
Let me know,
    Mark

On 9/12/11 3:59 PM, "Evan Culver"
reply@reply.github.com
wrote:

> Not sure if this is just a lack fo know-how on my part, but when I try to send
> tests to Selenium Grid, I'm seeing this error:
> 
> jute_submit_test --sh 192.168.0.87 --send_output -t path/to/my/test/test.html
> Submitting { tests: 'path/to/my/test/test.html',
>   retry: 0,
>   sel_host: '192.168.0.87',
>   sel_browser: '*firefox',
>   send_output: 1 } to my.hostname.com
> Problem contacting JUTE server at: eculver.mdr.iowalab.com:8080
> Is JUTE running there?  Did you specify '--host' and '--port' correctly?
> 
> JUTE server is running, I can connect and run test via web UI, but when I run
> this command, the server dies. In the log:
> 
> [Mon, 12 Sep 2011 22:57:41 GMT] "GET /jute/_get_test?d=1315868261208 HTTP/1.1"
> 200 - "http://my.hostname.com:8080/jute_docs/run_tests.html?" "Mozilla/5.0
> (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.1 (KHTML, like Gecko)
> Chrome/13.0.782.220 Safari/535.1"
> { tests: 'path/to/my/test/test.html',
>   retry: 0,
>   sel_host: '192.168.0.87',
>   sel_browser: '*firefox',
>   send_output: 1 }
> 
> node.js:134
>         throw e; // process.nextTick error, or 'error' event on first tick
>               ^
> Error: ECONNREFUSED, Connection refused
>     at Client._onConnect (net.js:601:18)
>     at IOWatcher.onWritable [as callback](net.js:186:12)

**Comment by eculver** [comment]
Ok, so it looks like the initial issue was due to connectivity issues as you suggested (Grid dying), but it looks like talking to Grid just hangs now. I'll open a new ticket when I have more information. 

FWIW, which versions of Selenium Grid were tested against?

Thanks,
Evan

**Comment by zzo** [comment]
It has been tested against: selenium-server-standalone-2.4.0.jar, the older 1.0.3 RC server, and 1.0.8 of the grid stuff.
It's not clear to me why JUTE would crash if it could not connect to the remote Selenium RC or Grid - what version of the Selenium Grid are you running??

**Comment by eculver** [comment]
Ok, so I think to close this ticket we should change the docs to mention that JUTE daemon must be running in order to submit a test to Selenium and catch connection errors, thus preventing the daemon from stopping, unless you feel a hard failure of the daemon is proper. It's just a little counter-intuitive I think. 

Also, it seems that the soda connection exception is never being reached in this case, which leads me to believe that something is going on before that can be caught. Thoughts?

I'll go ahead and create a separate issue relating more specifically to Selenium versions which is still a problem (ran against selenium-server-standalone-2.4.0.jar).

Thanks.

**Comment by zzo** [comment]
I have re-verified that jute/soda works against selenium-standalone 2.6.0 and the 1.x stuff.

As for the ECONNREFUSED causing the entire process to die - I have filed a bug against soda here:

https://github.com/LearnBoost/soda/issues/27

They need better error handling & unfortunately doesn't look like JUTE can handle it outside of soda.

Gonna play with grid now....

**Comment by eculver** [comment]
Yeah, I was thinking it was more of a soda bug than anything upon further inspection. Same thing goes for compatibility issues w/ Selenium since JUTE simply relies on soda for this piece. 

Thanks for checking it out.
