### ISSUE TITLE
Submit unittest through phantomjs doesn't generate test report 

### ISSUE THREAD

**Issue by haochen08** [zzo/JUTE#8]
It's OK to generate report via chrome browser but not for command line submit via phantomjs.
I have installed phantomjs already.

The console output says
    Submitting { tests: 'sum.html',
    retry: 0,
    phantomjs: true,
    screen: 0 } to {host machine}
  Final PhantomJS Results: {"current_results":{}}

I checked the log at /home/y/logs/jute.log
It has issue when dump report into file. The exact log is as follows:

{Host IP} - - [Mon, 02 Jan 2012 05:57:11 GMT] "PUT /jute/_message HTTP/1.1" 200 - 
"http://{hostname}:8080/test/sum.html" "M
ozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/533.3 (KHTML, like Gecko) PhantomJS/1.3.0 Safari/533.3"
MESSAGE console.log from /test/sum.html: JUTE TestDone SumSuite
TypeError: Cannot read property '0' of undefined
    at [object Object].testReport (/home/y/lib/node4/lib/node_modules/jute/jute/actions/testReport.js:62:45)
    at [object Object].emit (events.js:67:17)
    at [object Object].prune (/home/y/lib/node4/lib/node_modules/jute/jute/actions/prune.js:60:25)
    at [object Object].emit (events.js:72:17)
    at Object.<anonymous> (/home/y/lib/node4/lib/node_modules/jute/jute/server.js:84:21)
    at nextMiddleware (/home/y/lib/node4/lib/node_modules/jute/node_modules/connect/lib/middleware/router.js:175:25)
    at param (/home/y/lib/node4/lib/node_modules/jute/node_modules/connect/lib/middleware/router.js:183:16)
    at pass (/home/y/lib/node4/lib/node_modules/jute/node_modules/connect/lib/middleware/router.js:191:10)
    at Object.router [as handle](/home/y/lib/node4/lib/node_modules/jute/node_modules/connect/lib/middleware/router.js:197:6)
    at next (/home/y/lib/node4/lib/node_modules/jute/node_modules/connect/lib/http.js:203:15)
.....
Dumping /home/chenhao/jutebase/output/SumSuite/Mozilla5_0__X11_U_Linux_i686_en-US__AppleWebKit533_3__KHTML__like_Gecko__PhantomJS1_3_0_Safari533_3-tes
t.xml  
ERROR: Error dumping file /home/chenhao/jutebase/output/SumSuite/Mozilla5_0__X11_U_Linux_i686_en-US__AppleWebKit533_3__KHTML__like_Gecko__PhantomJS1_3
_0_Safari533_3-test.xml: Error: EBADF, Bad file descriptor '/home/chenhao/jutebase/output/SumSuite/Mozilla5_0__X11_U_Linux_i686_en-US__AppleWebKit533_
3__KHTML__like_Gecko__PhantomJS1_3_0_Safari533_3-test.xml'

Is there any suggestion for this issue?

**Comment by zzo** [comment]
Does the path:  /home/chenhao/jutebase/output/
exist and writable by the jute process??

**Comment by haochen08** [comment]
What account does jute process use to access the folder. Does it use the same account by which i start it?

**Comment by haochen08** [comment]
Finally i resolved the issue, I found the directory must open write access to group for jute to generate the report under it
