### ISSUE TITLE
JUTE is missing dependency on jsdom

### ISSUE THREAD

**Issue by g13n** [zzo/JUTE#9]
Tried to run `jute_submit_test` and got an error for missing `jsdom` module.

```
$ jute_submit_test --v8 --test ./foo.js 
Error running jute_v8: Error: Command failed: 
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'jsdom'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jute/jute_v8.js:47:19)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
```

**Comment by zzo** [comment]
i have udpated the reqs to include both jsdom & htmlparser since yui3 doesn't include them anymore...

**Comment by g13n** [comment]
Thanks Mark.
